Added Contributors page
ComputerScienceHouse/devcade-website pull request #27
Opened 2023-03-12 17:14 UTC by wilsonmcdade

#19

2023-03-12 17:56 UTC, asimonson1125 requested changes
Styling the user boxes can wait, but we should probably do a quick scan of the group for links to add.  Off the top of my head:
asimonson.com
noahemke.com (offline?)
https://esoccoli.me/
Not critical, but  I'd have liked to see a JSON contributors list which is called and iterated over to generate the email hashes.  If the emails might be displayed elsewhere, hashing could be deferred to the html template to get the profile pictures of everyone involved in a single line.

2023-03-14 00:35 UTC, wilsonmcdade commented
Agree about waiting on box styling. Since we're just using game cards, that can be done whenever game cards are updated.

I added some of the personal sites, some ppl haven't gotten back with me with their website. 

I'd love to see this feature worked into the api or at least have some user-editable fields for this, but that requires some more planning

2023-03-14 00:43 UTC, MTFT-Games approved these changes
looks good to me so far

2023-03-14 00:53 UTC, asimonson1125 approved these changes

2023-03-14 03:27 UTC, merged