Update setup instructions + remove unused env vars
ComputerScienceHouse/devcade-website pull request #66
Opened 2023-12-10 20:33 UTC by Lontronix

The environment variables IP and PORT did not appear to be used so I removed them from config.py and the template envs.py in README.md

I also updated the template envs.py to have the minimum required environment variables to get the program up and running locally.

I wasn't able to get the program up and running locally using the previous instructions without a bunch of debugging.

2023-12-11 05:33 UTC, MTFT-Games requested changes
Other than broken link I will defer to someone that knows how flask works cc @esoccoli perhaps

2023-12-11 05:33 UTC, MTFT-Games commented on README.md
> +To do so using Podman](https://podman.io/), run the following commands from the root of the project directory:
This link has no opening bracket.

2023-12-11 19:16 UTC, esoccoli reviewed
I tested it with these instructions, and it worked. Once the link is fixed ill give it an approval

2023-12-11 23:58 UTC, Lontronix commented on README.md
> +To do so using Podman](https://podman.io/), run the following commands from the root of the project directory:
Good catch! Just fix it

2023-12-12 00:00 UTC, esoccoli approved these changes
lgtm

2023-12-12 00:03 UTC, MTFT-Games approved these changes

2023-12-12 00:03 UTC, merged